#! /usr/bin/python
## assumes CSV file will have counts of plays, structure like:
## Plays, `AlbumTitle`,`TrackTitle`, `TrackArtist`, `Artist`, `AddDate`, `AlbumId`,`Genre`

## how to make better:
## run on server, include DB call
## run on server as call that returns a download

import csv
import pprint

from openpyxl import Workbook
from openpyxl.styles import Font
from datetime import date

pp = pprint.PrettyPrinter(indent=4)

# for reference
columns = ['Plays', 'AlbumTitle','TrackTitle', 'TrackArtist', 'Artist', 'AddDate', 'AlbumId','Genre']

genres = [  "Unknown", "Bluegrass", "Blues", "Cajun", "Celtic", "Classical", "Country", "Folk",
            "Gospel", "Hip Hop", "International", "Jazz", "Lounge-Schlock", "Modern",
            "R & B", "Ragtime", "Rap", "Reggae", "Rock", "Soundtrack", "Space", "Spoken Word",
			"Techno", "Zydeco" ]


## update this or add argv functionality
## infile should be a CSV with columns defined as the columns var above
## csv should have a counts column, generated by mySQL queery.

infile = "SoundExchangePlaylist_033117_names.csv"

wb = Workbook()
d = date.today()
dest_filename = 'Charts_{}.xlsx'.format(d)

sheets = [ wb.create_sheet(title=g) for g in genres ]

## remove the default sheet
wb.remove_sheet( wb['Sheet'] )

## write headers to sheets
header = ['Plays', 'AlbumTitle','TrackTitle', 'Artist', 'AddDate', 'AlbumId','Genre']

# diff header order
h2 = ['Plays', 'Artist', 'Track','Album', 'Add Date', 'Album Id','Genre']

ft = Font(bold=True)


for g in genres:
	ws = wb[g]
	ws.append(h2)


# why doesn't this work?
for sheet in sheets:
	row = sheet.row_dimensions[1]
	row.font = Font(bold=True)


with open(infile, 'rb') as f:
	x = 0
	reader = csv.DictReader(f)

	for row in reader:
		x += 1

		# merge Artist, TrackArtist
		artist = row['TrackArtist'] + row['Artist']
		artist = artist.replace("NULL","")

		# build data row, convert plays and ID from string to int.
		# should be same order as header
		data = [ int(row['Plays']), row['AlbumTitle'], row['TrackTitle'],
		artist, row['AddDate'], int(row['AlbumId']), row['Genre'] ]

		## diff column order
		d2 = [ int(row['Plays']), artist, row['TrackTitle'], row['AlbumTitle'],
		row['AddDate'], int(row['AlbumId']), row['Genre'] ]

		genre = row["Genre"]

		if genre not in genres:
			genre = "Unknown"

		wb[genre].append(d2)

print "rows read >> ", x
print "writing to >> ", dest_filename


wb.save(filename = dest_filename)


# query = """SELECT Count(*) as Plays, AlbumTitle, TrackTitle, TrackArtist, Artist, AddDate, AlbumId, Genre
# FROM SoundExchangePlaylist
# WHERE StartDateTime between '2017-02-28 00:00:01' and NOW()
# GROUP BY TrackTitle, AlbumTitle
# ORDER BY Plays DESC;"""

