#! /usr/bin/python
## assumes CSV file will have counts of plays, structure like:
## Plays, `AlbumTitle`,`TrackTitle`, `TrackArtist`, `Artist`, `AddDate`, `AlbumId`,`Genre`

## how to make better:
## run on server, include DB call
## run on server as call that returns a download

import csv
import pprint

from openpyxl import Workbook
from datetime import date

pp = pprint.PrettyPrinter(indent=4)

columns = ['Plays', 'AlbumTitle','TrackTitle', 'TrackArtist', 'Artist', 'AddDate', 'AlbumId','Genre']

genres = [  "Unknown", "Bluegrass", "Blues", "Cajun", "Celtic", "Classical", "Country", "Folk",
            "Gospel", "Hip Hop", "International", "Jazz", "Lounge-Schlock", "Modern",
            "R & B", "Ragtime", "Rap", "Reggae", "Rock", "Soundtrack", "Space", "Spoken Word",
			"Techno", "Zydeco" ]


## update this or add argv functionality
## infile should be a CSV with columns defined as the columns var above
## csv should have a counts column, generated by mySQL queery.

infile = "SoundExchangePlaylist_033117_names.csv"

wb = Workbook();

d = date.today()
print d
dest_filename = 'Charts_{}.xlsx'.format(d)
print dest_filename

sheets = [ wb.create_sheet(title=g) for g in genres ]

## remove the default sheet
wb.remove_sheet( wb.get_sheet_by_name('Sheet') )

x = 0


with open(infile, 'rb') as f:
	reader = csv.DictReader(f)

	for row in reader:
		x += 1

		# merge Artist, TrackArtist
		artist = row['TrackArtist'] + row['Artist']
		artist = artist.replace("NULL","")

		# build data row, convert plays and ID from string to int.
		data = [ int(row['Plays']), row['AlbumTitle'], row['TrackTitle'],
		artist, row['AddDate'], int(row['AlbumId']), row['Genre'] ]

		genre = row["Genre"]

		if genre not in genres:
			genre = "Unknown"

		wb[genre].append(data)

print "rows read >> ", x
print "writing to >> ", dest_filename

wb.save(filename = dest_filename)


# query = """SELECT Count(*) as Plays, AlbumTitle, TrackTitle, TrackArtist, Artist, AddDate, AlbumId, Genre
# FROM SoundExchangePlaylist
# WHERE StartDateTime between '2017-02-28 00:00:01' and NOW()
# GROUP BY TrackTitle, AlbumTitle
# ORDER BY Plays DESC;"""

